---
- name: Test the cloud.terraform_ops.plan_stash role (stash functionality)
  hosts: localhost
  gather_facts: true
  vars:
    # terraform_existing_plan_url: ""
    terraform_existing_config_url: "https://raw.githubusercontent.com/mandar242/Test-Playbooks/main/main.tf"
    plan_stash_var_name_val: my_test_stashed_plan
    plan_stash_plan_file_path_val: ./myplan.tfplan
  tasks:

    - name: Download terraform config file and store as "main.tf"
      uri:
          dest: ./main.tf
          url: "{{ terraform_existing_config_url }}"
      when: terraform_existing_config_url is defined and terraform_existing_config_url | length != 0

    - name: Generate planfile by running Terraform plan
      cloud.terraform.terraform:
        project_path: ./
        force_init: true
        plan_file: "{{ plan_stash_generate_plan_file_name_val }}"
        state: present
      check_mode: true

    - name: Stash the Terraform plan file into variable "{{ plan_stash_var_name_val }}"
      ansible.builtin.include_role:
        name: cloud.terraform_ops.plan_stash
      vars:
        plan_stash_operation: stash
        plan_stash_var_name: "{{ plan_stash_var_name_val }}" # if not provided, defaults to "terraform_plan"
        plan_stash_plan_file_path: "{{ plan_stash_generate_plan_file_name_val }}"